name: Schedule

on:
    schedule:
        - cron: '*/5 * * * *'

    workflow_dispatch:

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: sh
              run: ls -l
