name: Schedule

on:
    schedule:
        - cron: '*/5 * * * *'

    workflow_dispatch:

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: sh
              run: sh /home/runner/work/test/test/server_check.sh
              shell: bash
